### ISSUE TITLE
lmao i cant talk in discord so im using this place instead

### ISSUE THREAD

**Issue by Taureon** [Taureon/aps-plus-plus-addons#3]

**Comment by Taureon** [comment]
anyway what if someone hosted a matrix server so we wouldnt have to rely on discord

**Comment by archbtww** [comment]
I could do that if you want

**Comment by AydanL** [comment]
wut a matrix server

**Comment by Anguish-Fusion** [comment]
Fr lol what is it, oh yeah btw I also can't talk in discord _lmao_

**Comment by AydanL** [comment]
uh what? discord is back rn

**Comment by Anguish-Fusion** [comment]
Nvm
What I meant is that I can't talk in the server

**Comment by letsluke07** [comment]
no need matrix server, we are in a matrix already frfr
