### ISSUE TITLE
Whirlwind satilet speed

### ISSUE THREAD

**Issue by waitwhatglitch** [Taureon/aps-plus-plus-addons#9]
I think i figured out why it speeds up, when you switch tank it keeps the controller and it adds a second one.
i will investigate further and try to come up with a fix.

**Comment by waitwhatglitch** [comment]
after further testing i think i am wrong.

**Comment by waitwhatglitch** [comment]
Nope im right. if you remove the controller from tornado and upgrade to it, it does not speed up. but it becomes off center.

**Comment by waitwhatglitch** [comment]
If you remove "CONTROLLERS: ["whirlwind"]," from every tank expect the orginal whirlwind it fixes the problem.  @Zenphia

**Comment by TheGreenSquare** [comment]
![image](https://github.com/Taureon/aps-plus-plus-addons/assets/93544652/d26dc69b-987a-4d38-b1fd-d09e1f75c7e8)
That leads to issues if you _aren't_ upgrading to a whirlwind-branch tank from the whirlwind.

**Comment by waitwhatglitch** [comment]
so you are saying we need a way to check if it already has the controller, and if it does, dont add it again. which i tried for 30 minutes and got nowhere.

**Comment by TheGreenSquare** [comment]
already fixed in OSA
